### ISSUE TITLE
Finalize Travel Route Template

### ISSUE THREAD

**Issue by moritzhubl** [trackfellas/homepage#28]
Tasks to achieve:

- [x] Whole Template: Reduce Space between Headlines (see between Main transportation & galeria are like 6 lines space)

- [x] Trackfella: Over the Picture; Add Name before Nika, space before and after (25-35); Submitted Routes in a new line; Contact me in big font
- [x] Google API bigger for better zoom in; I would say hight is at least half of the width.
- [x] Change Colour of Destination overview to brown, as it is not part of the travel route itself which is red
- [x] Trip details: Stars of the rating with the same spacing! Maybe putting the rating on the right side?
- [x] Visualisation between stations (first: transport icon, arrow down: fa-arrow-down, Rating)
- [x] Include Highlights & No-Gos: - in trip details: Highlight as fa-trophy, No-go as fa-exclamation-triangle; extra section with highlights & nogos! Add symbols as a legend over the trip details
- [x] Integration of Feedback Form
- [x] Popup of Feedback Form
- [x] Social Share Buttons: Bigger & without text, but with the logo ;) 
- [x] target blank route details
- [x] in Transportation: a bit more space between the transportation icon, the arrow down and the rating

**Comment by nikamaack** [comment]
Beim Footer keinen hover in rot, sondern bitte unterstreichen und bei weiß bleiben, Striche für Abstände anpassen und Höhe der Wörter oder ggf. nur etwas drüber
