### ISSUE TITLE
Final Update Cuba Route:

### ISSUE THREAD

**Issue by moritzhubl** [trackfellas/homepage#29]
Final Update of Cuba Route:

- [x] Update Name of Route to "Cuba Southeast Cities Tour"
Add Rating to Trip Name "(4/5)"

- [x] Havanna: - La Trorre: Add "fa-trophy" to visualise it as a highlight

- [x] Trinidad: - Add "fa-trophy" to visualise it as a highlight
 All "TIP" in new line;  Accomodation:.... “Type” in new line

- [x]  Transportation between Camagüey and Bayamo: Delete: First “Type: Transportation and empty lines”

- [x] Santiage de Cuba: Add to Tip in a new line: 
"There is also a train connection from Santiago de Cuba over Camagüey and Santa Clara to Havanna every few days, which takes about 16 hours overnight and might be a nice alternative to travel with locals. Prices between 63 CUC and 30 CUC are reasonable, but you will have to buy the tickets up to 5 days in advance from the station your are leaving from. Bring your passport. For more infos check out: http://www.seat61.com/Cuba.htm#How%20to%20book"

- [x] Add Sightseeing in Santiago de Cuba:
"Santa Ifigenia Cemetery (4/5) Add link: http://www.santiagodecubacity.org/en/architecture/santa-ifigenia-cemetary.html
Type: Historical sight, Walking tour
Transportation: Taxi
Entry: free
Comment: If you have time you should visit the cemetery. It's in the northwest of Santiago de Cuba. Take a nice walk down to the harbour and catch a bicycle-taxi. You will pass the train station and the old "Bacardi-factory". One of the most visited places in the churchyard is the big Mausoleum that keeps the ashes of one of the most important National Heros "José Martí".

Antonio Maceo Revolution Square (3/5) Add link: http://www.santiagodecubacity.org/en/architecture/antonio-maceo-square.html
Type: Historical sight
Transportation: by Foot
Comment: This square is very close to the Viazul busstation and here you can find the highest statue in the whole country in honor to the hero Antonio Maceo Grajale

Cathedral (4/5) add Link: http://www.santiagodecubacity.org/en/architecture/cathedral-asuncion.html
Type: Historical sight, city center
Transportation: by Foot
The Square around the cathedral is very famous and beautiful. Here you can find a little park, the town hall and the oldest house from Cuba (build in 1516).

- [x] Guanatanamo: "Tip" in new line; Update Tip: "Better head east to isolated Baracoa with its rich nature, beaches and the National Park Alejandro de Humboldt."
Add in new line "Comment: I stayed in a casa particulares for locals, but you will find nice in the BnB's in the center."
Delete Accomodation in Guantanamo!

- [x]  Update Rating of transportation from Guantanamo to Havanna to 4 stars

**Comment by niklashof** [comment]
readd spaces

**Comment by niklashof** [comment]
done in: #47
